### ISSUE TITLE
User, Main profile image won't upload

### ISSUE THREAD

**Issue by Mark-Jefferson** [SummerTreeDesigns/WedWishes#29]
I tried to upload a Main profile image and received the error message, see screenshot.
https://drive.google.com/open?id=0B8YmuQMr98J_YkZadl9XYVVrM2M&authuser=0

**Comment by le-darshan** [comment]
this error is fixed now i am not facing this error while uploading user's photo can you test it.

**Comment by Mark-Jefferson** [comment]
I am still getting the same error in the screenshot above. I have tried using different photos and always the same error. I will try again from a different computer also.

**Comment by Mark-Jefferson** [comment]
I have tried on Chrome, Firefox, IE, and all have the same error. Also the small circle next to the All media items drop list will not stop spinning. That may be why its causing an erorr, it could be trying to load some media items it can not find.
